
version: '3.9'

services:
  database:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
    env_file:
      - ./data/.env
    restart: always
    networks:
      - main
      
  
  cache:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - main

  app:
    build: registry.gitlab.com/zebco/player-tracker:latest
    container_name: player-tracker
    depends_on:
      - database
      - cache
    restart: on-failure
    networks:
      - main

networks:
  main:
